"use client"

import { useEffect, useState } from "react"
import api from "@/lib/api"

type Provider = "gmail" | "outlook" | "zoho" | "custom"

type Props = {
  projectId: string
}

export default function SmtpConfig({ projectId }: Props) {
  const [provider, setProvider] = useState<Provider>("gmail")

  const [form, setForm] = useState({
    username: "",
    password: "",
    host: "",
    port: "",
  })

  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [error, setError] = useState("")

  useEffect(() => {
    loadConfig()
  }, [])

  const loadConfig = async () => {
    try {
      const res = await api.smtp.me(projectId)
      const data = res.data.data

      if (!data || data.provider === "flux") return

      setProvider(data.provider)
      setForm({
        username: data.username || "",
        password: "",
        host: data.host || "",
        port: data.port ? String(data.port) : "",
      })
    } finally {
      setLoading(false)
    }
  }

  /* ------------------------
     Save config
  ------------------------- */
  const saveConfig = async () => {
    try {
      setSaving(true)
      setError("")

      const payload = {
        provider,
        username: form.username,
        password: form.password,
        host: provider === "custom" ? form.host : null,
        port:
          provider === "custom" && form.port
            ? Number(form.port)
            : null,
      }

      await api.smtp.save(projectId, payload)

      setSaved(true)
      setForm(prev => ({ ...prev, password: "" }))
      setTimeout(() => setSaved(false), 2500)
    } catch (err: any) {
      setError(
        err?.response?.data?.message || "Failed to save SMTP config"
      )
    } finally {
      setSaving(false)
    }
  }

  if (loading) return null

  return (
    <section className="space-y-4 p-4 border rounded-md">
      <h3 className="font-medium">SMTP Configuration</h3>

      {/* PROVIDER */}
      <div className="space-y-1">
        <label className="text-sm font-medium">Email Provider</label>
        <select
          value={provider}
          onChange={e =>
            setProvider(e.target.value as Provider)
          }
          className="w-full px-3 py-2 border rounded-md text-sm"
        >
          <option value="gmail">Gmail</option>
          <option value="custom">Custom SMTP</option>
        </select>
      </div>

      {/* CUSTOM SMTP */}
      {provider === "custom" && (
        <>
          <input
            value={form.host}
            onChange={e =>
              setForm(prev => ({ ...prev, host: e.target.value }))
            }
            placeholder="SMTP Host (e.g. smtp.example.com)"
            className="w-full px-3 py-2 border rounded-md text-sm"
          />

          <input
            value={form.port}
            onChange={e =>
              setForm(prev => ({ ...prev, port: e.target.value }))
            }
            placeholder="SMTP Port (e.g. 587)"
            className="w-full px-3 py-2 border rounded-md text-sm"
          />
        </>
      )}

      {/* EMAIL */}
      <input
        value={form.username}
        onChange={e =>
          setForm(prev => ({ ...prev, username: e.target.value }))
        }
        placeholder="Email address"
        className="w-full px-3 py-2 border rounded-md text-sm"
      />

      {/* PASSWORD */}
      <input
        type="password"
        value={form.password}
        onChange={e =>
          setForm(prev => ({ ...prev, password: e.target.value }))
        }
        placeholder="App password"
        className="w-full px-3 py-2 border rounded-md text-sm"
      />

      {/* INFO */}
      <div className="text-sm text-amber-700 bg-amber-50 p-3 rounded-md">
        <strong>Do NOT use your email password.</strong>
        <br />
        Use an App Password generated by your email provider.
        <br />
        <a
          href="https://support.google.com/accounts/answer/185833"
          target="_blank"
          className="underline"
        >
          How to create a Gmail App Password
        </a>
      </div>

      {error && (
        <p className="text-sm text-red-600">{error}</p>
      )}

      {/* ACTIONS */}
      <div className="flex items-center gap-3">
        <button
          onClick={saveConfig}
          disabled={saving}
          className="px-4 py-2 bg-black text-white rounded-md"
        >
          {saving ? "Saving..." : "Save SMTP"}
        </button>

        {saved && (
          <span className="text-green-600 text-sm">
            Saved
          </span>
        )}
      </div>
    </section>
  )
}
